# Generated by Django 5.0.1 on 2024-02-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
