import React, { useState, useEffect } from "react";
import { api } from "../../../utils/api";
import debounce from "lodash/debounce";

interface TitleInputProps {
  initialTitle?: string;
  initialSlug?: string;
  initialURL?: string;
  onTitleChange: (title: string) => void;
  //   onSlugChange: (slug: string) => void;
  onURLChange: (url: string) => void;
}

const TitleInput: React.FC<TitleInputProps> = ({
  initialTitle = "",
  initialSlug = "",
  initialURL = "",
  onTitleChange,
  onURLChange,
}) => {
  const [title, setTitle] = useState(initialTitle);
  const [slug, setSlug] = useState(initialSlug);
  const [url, setURL] = useState(initialURL);

  const generateSlug = debounce(async (title: string) => {
    try {
      const response = await api.post("/slugify/", { title });
      const generatedSlug = response.data.slug;
      setSlug(generatedSlug);
    } catch (error) {
      console.error("Error generating slug:", error);
    }
  }, 500);

  useEffect(() => {
    if (title) {
      generateSlug(title);
    }
  }, [title, generateSlug]);

  useEffect(() => {
    setTitle(initialTitle);
    if (initialTitle) {
      generateSlug(initialTitle);
    }
  }, [initialTitle, generateSlug]);

  const useAutoGeneratedSlug = () => {
    setURL(slug);
    onURLChange(slug);
  };

  const postURL = "https://danielsunghyunpark.com/post/".concat(url);

  return (
    <div>
      <div className="mb-4">
        <label className="block text-gray-700 text-sm font-bold mb-2">
          Title
        </label>
        <input
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          type="text"
          value={title}
          onChange={(e) => {
            const newTitle = e.target.value;
            setTitle(newTitle);
            onTitleChange(newTitle);
          }}
        />
      </div>
      <div className="flex space-x-3 mb-4">
        <div className="flex-1">
          <label className="block text-gray-700 text-sm font-bold mb-2">
            URL
          </label>
          <input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            type="text"
            value={url}
            onChange={(e) => {
              const newSlug = e.target.value;
              setURL(newSlug);
              onURLChange(newSlug);
            }}
          />
          <div className="sub_url_desc text-[10px] text-gray-600 mt-2">
            {postURL}
          </div>
        </div>
        <div className="flex items-end mb-[21px]">
          <button
            type="button"
            className="px-4 py-2 bg-gray-300 text-gray-700 rounded"
            onClick={useAutoGeneratedSlug}
          >
            Use Slug
          </button>
        </div>
        <div className="flex-1">
          <label className="block text-gray-700 text-sm font-bold mb-2">
            Auto-Generated Slug
          </label>
          <input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            type="text"
            value={slug}
            onChange={(e) => {
              const newSlug = e.target.value;
              setSlug(newSlug);
              onURLChange(newSlug);
            }}
            disabled
          />
        </div>
      </div>
    </div>
  );
};

export default TitleInput;
